version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: Maria
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: house_db
    volumes:
      - /home/maria/dockerproject2/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "listen_addresses=0.0.0.0"]

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - /home/maria/dockerproject2:/app
      - /home/maria/dockerproject2/postgresql-42.7.1.jar:/opt/bitnami/spark/jars/postgresql-42.7.1.jar
    ports:
      - "4040:4040"
    depends_on:
      - postgres
    command: ["/opt/bitnami/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]

  spark-worker1:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    command: ["/opt/bitnami/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]

  spark-worker2:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    command: ["/opt/bitnami/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]

